### ISSUE TITLE
有效位数是52位吧

### ISSUE THREAD

**Issue by fengmumu1** [akira-cn/FE_You_dont_know#9]
Js 使用双精度，然后64位来存，一个符号位，11个指数位，52个有效数字（默认取到0.xxxx，只存点后面的东西）

**Comment by akira-cn** [comment]
文章里说的53位有效范围，是包括符号位在内的，范围是-2^53 + 1 到 2^53 -1，我们通常说二进制位数的时候是包括符号位的。比如说Int32，包括31位有效数字和1个符号位，但是我们说32位整数，而不是说31位整数。
